### ISSUE TITLE
Plan for releasing 0.1 version

### ISSUE THREAD

**Issue by ekexium** [tikv/client-rust#171]
We're going to make the project ready for a 0.1 release in the following weeks. Please leave a comment if you have suggestions!

We expect it to be fully functional in most cases, and enable Rust users to freely play with TiKV. Becaues of the publish blocker #32 , we will probably not publish it on crate.io. 

Supported functionalities in 0.1:
- Raw API
  - `put`, `get`, `delete`, `scan`, `batch_put`, `batch_get`, `batch_delete`, `batch_scan`, `delete_range`
- Transactional API (optimistic) 
  - `begin`, `commit`, `rollback`, `put`, `get`, `delete`, `scan`, `batch_get`, `lock`

Checklist:
- Functionality
  - [x] ~Whether to remove `delete_range`~ `delete_range` is currently supported by TiKV.
  - [x] ~GC will not be provided in 0.1~ #180
- Bugfix and test
  - [x] Encoding problem #162 
  - [x] Parameters of `group_keys_by_region` must be sorted #162 
  - [x] Some requests only sends to the first region because of misuse of `stream.into_future` #176 
  - [x] For end_key, `None` and `Some(empty)` should both mean unbounded, while in some palces we miss the second situation. We cannot only use `None` to represent unbounded because parameters is first converted into kvproto request parameters (which is Vec<u8>). Related PR: #162, #174, #179 . There are probably more.
  - [x] `limit` only applies to each region for raw_scan and raw_batch_scan #179 
  - [x] Integration tests
    - [x] raw
    - [x] transactional
- Usability
  - [x] Consistent naming: `put`/`set`, `key_only`/`with_key_only`, etc.
  - [x] `batch_get` returns `Iter<Option<KvPair>>`, while may not contain all non-existent entries. #173 
- Robustness
  - [x] Do not panic when error happens
  - [ ] ~~[Jepsen Test](https://github.com/tikv/tikv/issues/9588)~~
- Documentation
  - [x] Tutorial for user #170 
- Examples and use cases

**Comment by nrc** [comment]
I'm thinking of the 0.1 release again. I think we should aim for the end of March. I've added some issues which I think should be blocking to the 0.1 milestone.

I don't think we need to block on the Jepsen test, though we should probably block a 1.0 on that.

@ekexium are you aware of anywhere where we panic where we should create an error?

**Comment by ekexium** [comment]
> I don't think we need to block on the Jepsen test, though we should probably block a 1.0 on that.

Agree.

> are you aware of anywhere where we panic where we should create an error?

I checked it months ago. Recently we've added more functionalities. I'll check it again.

Will we also publish the support of pessimistic transactions and async commit? There is a lack of tests I think.

**Comment by nrc** [comment]
> Will we also publish the support of pessimistic transactions and async commit? There is a lack of tests I think.

Pessimistic transactions yes, async commit no (because we haven't implemented recovery). I think there are enough tests for pessimistic transactions, though I might be wrong. In any case, we don't need to be perfect for a 0.1 launch.

This makes me wonder if we should have a feature flag system for experimental features like async commit, or whether we should just `#[doc(hidden)]` them.

**Comment by nrc** [comment]
Everything here is done
