### ISSUE TITLE
Tracking issue: documentation

### ISSUE THREAD

**Issue by nrc** [tikv/client-rust#194]
## For initial release

- [ ] Introduction (readme, include in rustdoc, check crate root docs)
- Public API of main crate
  - [ ] RawClient
  - [ ] ColumnFamily
  - [ ] TransactionClient
  - [ ] Snapshot
  - [ ] Transaction
  - [ ] Config
  - [ ] SecurityManager
  - [ ] BoundRange
  - [ ] Error
  - [ ] ErrorKind
  - [ ] Key
  - [ ] KvPair
  - [ ] Result
  - [ ] Timestamp
  - [ ] ToOwnedRange
  - [ ] Value
  - [ ] Region
  - [ ] RegionId
  - [ ] RegionVerId
  - [ ] StoreId
- [ ] examples (each example is introduced, well-commented, linked from docs)

## For later

- [ ] Public API of all crates

**Comment by nrc** [comment]
There's still a lot of work to do here, but I believe that #269 gets us to a state where we can make a 0.1 release.
